= Welcome to GitHub Copilot for Programmers

image:https://imagedelivery.net/VKawrzTPdVOU6XYN26Rvmg/088a026f-2b4d-48d8-970f-766fbddfcf00/public[title="Web Age Solutions Logo"]

Since 1999, Web Age Solutions has been committed to helping our clients thrive. Whether that’s through off-the-shelf-courses or fully customized programs, we tailor our offerings to meet client needs.

== Schedule

=== Class Times

* Friday: 8:30 am to 11:30 am ET

=== Breaks

* Morning: 9:45 am to 10:00 am ET

== Outline Summary

* Welcome
* Copilot Overview
* Using Copilot in the IDE
* Using Copilot Chat in the IDE
* Experience the Intuitive Nature of Copilot Chat
** Explore a "new" language
** Explore and configure build tools
** Explore unit testing
** Explore source control
* Use Copilot In-Editor Suggestions
* Copilot Chat Beyond Programming
** VSCode
** Terminal
* Prompts and Suggestions
* X-Shot Prompting
* Refactoring Code with Copilot
* Fix Source Code Problems
* Questions and Answers
* Conclusion

== Courseware

* link:https://github-copilot-for-programmers.t4p.dev[Course Content]

== License

We provide the content in this repository for the class participants under the following link:./LICENSE[license]. GitHub provides the course slide deck and is not for redistribution. Atmosera provides the course outline and is not for redistribution. Cloud Contraptions LLC and its subsidiaries offer the remaining course content, which is not for redistribution.

++++
<br><br>
Course content and teaching is provided by:
<br><br>
++++

image:https://imagedelivery.net/VKawrzTPdVOU6XYN26Rvmg/aff3f165-00ec-4130-83d3-7ff4744f7d00/h=50,sharpen=1[link="https://www.cloudcontraptions.com",title="Cloud Contraptions Logo"]

image:https://imagedelivery.net/VKawrzTPdVOU6XYN26Rvmg/f68108cf-87fb-405c-3c7b-f941409cb200/h=50,sharpen=1[link="https://www.training4programmers.com",title="Training 4 Programmers Logo"]

